services:
  ovenmediaengine:
    image: packages.buildkite.com/ovenmediaengine/docker/ovenmediaengine-enterprise
    container_name: ovenmediaengine
    restart: unless-stopped
    environment:
      - OME_LICENSE_KEY=${OME_LICENSE_KEY}
      - OME_HOST_IP=${OME_HOST_IP}
    network_mode: host
    # ports:
    #   - 1935:1935
    #   - 8080:8080
    #   - 9999:9999/udp
    #   - 9000:9000
    #   - 3333:3333
    #   - 3478:3478
    #   - 10000-10009:10000-10009/udp
    volumes:
      - ./origin_conf:/opt/ovenmediaengine/bin/origin_conf
      - ./logs:/var/log/ovenmediaengine
      - ./ovenstudio:/opt/ovenmediaengine/ovenstudio
      - ./ovenstudio/data:/opt/ovenmediaengine/ovenstudio/data
      - ./delivery:/opt/ovenmediaengine/delivery
      - ./delivery/conf:/opt/ovenmediaengine/delivery/conf